### ISSUE TITLE
Upgrading to v2.0.19.0 fails during migration

### ISSUE THREAD

**Issue by lukeroberts** [PureStorage-Connect/SCOM-Management-Pack#14]
The msi runs successfully on our primary management server, but when we launch the MpMigrationTool.exe and select the 'upgrade' workflow the exe hard crashes during the search for overrides. We are attempting to upgrade from v1.2.20.0 to v2.0.19.0 The following are events in the application log for the crash:

```
Log Name:      Application
Source:        .NET Runtime
Date:          5/31/2023 9:02:26 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <REDACTED>
Description:
Application: MpMigrationTool.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at PureManagementPackUpgradeTool.DO.TemplateInfo.WriteXml(System.Xml.XmlWriter, PureManagementPackUpgradeTool.XmlSerializersCache)
   at PureManagementPackUpgradeTool.PackOverridesStore`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].WriteXmlPackElements(System.Collections.Generic.IList`1<PureManagementPackUpgradeTool.IPackElement`1<System.__Canon>>, System.Xml.XmlWriter)
   at PureManagementPackUpgradeTool.PackOverridesStore`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Store(System.Xml.XmlWriter, System.__Canon, System.Collections.Generic.ICollection`1<System.__Canon>, System.Collections.Generic.ICollection`1<System.__Canon>)
   at PureManagementPackUpgradeTool.PackOverridesStore`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Store(System.__Canon, System.Collections.Generic.ICollection`1<System.__Canon>, System.Collections.Generic.ICollection`1<System.__Canon>)
   at MpMigrationTool.Model.ProcessData`4[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].SaveState()
   at MpMigrationTool.Model.Manager`4+<>c__DisplayClass22_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<DiscoverPackEnvironment>b__1()
   at MpMigrationTool.Model.Manager`4+BusyGuard+<>c__DisplayClass4_0[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Invoke>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at MpMigrationTool.App.Main()
```

```
Log Name:      Application
Source:        Application Error
Date:          5/31/2023 9:02:26 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <REDACTED>
Description:
Faulting application name: MpMigrationTool.exe, version: 1.0.0.0, time stamp: 0xd99be0f0
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x087b084e
Faulting process id: 0x1c40
Faulting application start time: 0x01d993c01b03c964
Faulting application path: C:\Program Files\Pure Storage\Flash Array Management Tool\MpMigrationTool.exe
Faulting module path: unknown
Report Id: ec31a859-93b3-44fa-97b4-51b57ce731fb
Faulting package full name: 
Faulting package-relative application ID: 
```

[Report_5-31-2023.txt](https://github.com/PureStorage-Connect/SCOM-Management-Pack/files/11614476/Report_5-31-2023.txt)

**Comment by ChiefCyberPapa** [comment]
Here I am almost two years later with the same issue, and no resolution. If you found a solution, please share!

**Comment by lukeroberts** [comment]
Sadly no solution; I reverted to previous version and since we never got an answer I haven’t attempted again

What version SCOM are you trying this on (also what version of Windows)?

**Comment by lukeroberts** [comment]
Figured out this was due to something incorrect in the MP that I was storing the arrays in through the Pure monitoring wizard in SCOM. There was a subset that were using a malformed or incorrect Discovery TypeID. Not sure how exactly, but after cleaning this up, I was able to upgrade to the latest version
